server:
    port: ${SERVER_PORT:8080}

spring:
    application:
        name: rupiapp
    datasource:
        url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    security:
        jwt:
            secret-key: ${JWT_SECRET_KEY}
            expiration-time: ${JWT_EXPIRATION_TIME}
            refresh-token:
                secret-key: ${JWT_REFRESH_SECRET_KEY}
                expiration-time: ${JWT_REFRESH_EXPIRATION_TIME}
    jackson:
        property-naming-strategy: SNAKE_CASE
    mail:
        host: ${MAIL_HOST}
        port: ${MAIL_PORT}
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: ${MAIL_SMTP_AUTH:true}
                    starttls:
                        enable: ${MAIL_SMTP_STARTTLS_ENABLE:true}